### PR TITLE
Correct some paths for proper standalone generation

### PR DESCRIPTION
**Pull request by Fr0stbyteR**
Some of pthe paths in the static files starts with / which forces the webpage being under a directory of the root of the site. 
Using relative paths to avoid the issue.

### CODE REVIEW

**Comment by sletz** [comment]
This` /FAUST_DSP/XXX` patch model is needed when several PWA are generated. So I cannot merge this PR. Do you see a better way to handle multiple PWA ?

**Review by Fr0stbyteR — COMMENTED** [review]
Sorry I didn't cleanly based on the master branch, I can do another PR,

For the `/FAUST_DSP/XXX`, it simply doesn't exist if the files are under other directory (e.g. `localhost/` or `localhost/other_dir/something_else/`) than `localhost/FAUST_DSP`, changing to relative path should do the same thing and will be compatible with other paths. It needs some test but I don't see why it can break the PWA.

**Comment by sletz** [comment]
This is what I did first, but it was not working correctly when deploying several applications. So I had to use this "/FAUST_DSP/XXX" model  following what is explained here https://web.dev/articles/building-multiple-pwas-on-the-same-domain?hl=fr , so starting from a root and use /APP1, /APP2 kind of naming.

**Comment by Fr0stbyteR** [comment]
The article was not very clear about what to do exactly, I tried a fork of your site https://github.com/Fr0stbyteR/sletz.github.io deployed to https://fr0stbyter.github.io/sletz.github.io/ which works imo. The only trick is that each install clear the cache of another pwa. you need to reload the previous pwa online, then both should work offline.

**Comment by Fr0stbyteR** [comment]
The assets and the generated files are now renamed since we no longer will need to put multiple DSPs into the same directory. Now it emits following files:
- `index.html` main HTML file for standalone mode,
- `index.js` main JS file that loads the DSP with the HTML page,
- `dsp-module.wasm` main DSP WebAssembly module,
- `dsp-meta.json` DSP metadata,
- `mixer-module.wasm` (optional) mixer module for polyphonic instruments
- `effect-module.wasm` (optional) effect DSP module for polyphonic instruments
- `effect-meta.json` (optional) effect metadata for polyphonic instruments

**Pull request closed without merging**
